[project]
name = "workshop_testing"
version = "0.1.0"
description = "A workshop on testing acceptance"
readme = "README.md"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["task", "todo", "utils"]
